# Generated by Django 3.1.7 on 2021-04-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='pass_mark',
            new_name='pass_percentage',
        ),
    ]
