# Generated by Django 3.1.7 on 2021-04-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0002_auto_20210414_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.IntegerField(default=666666),
        ),
    ]
