# Generated by Django 3.1.7 on 2021-04-14 08:06

import Quizes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0005_auto_20210414_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.IntegerField(blank=True, default=Quizes.models.unique_code_generator, null=True),
        ),
    ]
