# Generated by Django 3.1.7 on 2021-04-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0009_auto_20210414_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=320),
        ),
    ]
