# Generated by Django 3.1.7 on 2021-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0010_auto_20210414_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=32),
        ),
    ]
