# Generated by Django 3.1.7 on 2021-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0012_remove_question_is_multi_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=62),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(default='Not metioned', max_length=40),
        ),
    ]
